@endpoint=https://btm0ljuqu0.execute-api.eu-central-1.amazonaws.com/prod/

GET {{endpoint}}/hello
###

GET {{endpoint}}/spaces?spaceId=a283c575-85c7-4392-a6c4-dc075b059528
###

GET {{endpoint}}/spaces?location=London
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "London",
    "name": "Best location"
}
###

